// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: comdex/liquidation/v1beta1/vault.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type LockedVault struct {
	LockedVaultID uint64                                 `protobuf:"varint,1,opt,name=locked_vault_id,json=lockedVaultId,proto3" json:"locked_vault_id,omitempty" yaml:"id"`
	VaultID       uint64                                 `protobuf:"varint,2,opt,name=vault_id,json=vaultId,proto3" json:"vault_id,omitempty" yaml:"id"`
	PairID        uint64                                 `protobuf:"varint,3,opt,name=pair_id,json=pairId,proto3" json:"pair_id,omitempty" yaml:"pair_id"`
	Admin         string                                 `protobuf:"bytes,4,opt,name=admin,proto3" json:"admin,omitempty" yaml:"owner"`
	VaultOwner    string                                 `protobuf:"bytes,5,opt,name=vault_owner,json=vaultOwner,proto3" json:"vault_owner,omitempty" yaml:"vault_owner"`
	AmountIn      github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,6,opt,name=amount_in,json=amountIn,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount_in" yaml:"amount_in"`
	AmountOut     github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,7,opt,name=amount_out,json=amountOut,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount_out" yaml:"amount_out"`
}

func (m *LockedVault) Reset()         { *m = LockedVault{} }
func (m *LockedVault) String() string { return proto.CompactTextString(m) }
func (*LockedVault) ProtoMessage()    {}
func (*LockedVault) Descriptor() ([]byte, []int) {
	return fileDescriptor_9a352ad2e51cdb9e, []int{0}
}
func (m *LockedVault) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LockedVault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LockedVault.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LockedVault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LockedVault.Merge(m, src)
}
func (m *LockedVault) XXX_Size() int {
	return m.Size()
}
func (m *LockedVault) XXX_DiscardUnknown() {
	xxx_messageInfo_LockedVault.DiscardUnknown(m)
}

var xxx_messageInfo_LockedVault proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LockedVault)(nil), "comdex.liquidation.v1beta1.locked_vault")
}

func init() {
	proto.RegisterFile("comdex/liquidation/v1beta1/vault.proto", fileDescriptor_9a352ad2e51cdb9e)
}

var fileDescriptor_9a352ad2e51cdb9e = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0x41, 0x6b, 0xd4, 0x40,
	0x14, 0xc7, 0x13, 0xdb, 0x26, 0xdd, 0xb1, 0xd5, 0x3a, 0x88, 0x84, 0x22, 0x33, 0x65, 0x0e, 0x4b,
	0x2f, 0x4d, 0x28, 0xa5, 0x08, 0x1e, 0xa3, 0x08, 0x01, 0xa1, 0x92, 0x83, 0x82, 0x97, 0x30, 0xc9,
	0xa4, 0xeb, 0xd0, 0x24, 0xb3, 0x26, 0x93, 0xd5, 0x7e, 0x0b, 0x3f, 0x86, 0x1f, 0x65, 0x8f, 0x3d,
	0x8a, 0x87, 0x41, 0xb3, 0x17, 0xcf, 0xf9, 0x04, 0x92, 0x99, 0x50, 0xb2, 0xe0, 0xc5, 0xd3, 0xbc,
	0x37, 0xff, 0xff, 0xef, 0xfd, 0xdf, 0xe1, 0x81, 0x79, 0x26, 0x4a, 0x96, 0x7f, 0x0d, 0x0a, 0xfe,
	0xb9, 0xe5, 0x8c, 0x4a, 0x2e, 0xaa, 0x60, 0x75, 0x9e, 0xe6, 0x92, 0x9e, 0x07, 0x2b, 0xda, 0x16,
	0xd2, 0x5f, 0xd6, 0x42, 0x0a, 0x78, 0x6c, 0x7c, 0xfe, 0xc4, 0xe7, 0x8f, 0xbe, 0xe3, 0xa7, 0x0b,
	0xb1, 0x10, 0xda, 0x16, 0x0c, 0x95, 0x21, 0xc8, 0x9f, 0x1d, 0x70, 0x50, 0x88, 0xec, 0x26, 0x67,
	0x89, 0x1e, 0x04, 0xdf, 0x80, 0xc7, 0xd3, 0x3e, 0xe1, 0xcc, 0xb3, 0x4f, 0xec, 0xd3, 0xdd, 0x10,
	0x75, 0x0a, 0x1f, 0xbe, 0xd5, 0xd2, 0xfb, 0x41, 0x89, 0x5e, 0xf7, 0x0a, 0xcf, 0x6e, 0x69, 0x59,
	0xbc, 0x24, 0x9c, 0x91, 0xf8, 0xb0, 0x98, 0x68, 0x0c, 0x5e, 0x80, 0xfd, 0xfb, 0x01, 0x0f, 0xf4,
	0x00, 0xaf, 0x53, 0xd8, 0xfd, 0x27, 0xea, 0xae, 0x46, 0xe8, 0x12, 0xb8, 0x4b, 0xca, 0xeb, 0x81,
	0xd9, 0xd1, 0xcc, 0xf3, 0x4e, 0x61, 0xe7, 0x1d, 0xe5, 0xb5, 0x46, 0x1e, 0x19, 0x64, 0xb4, 0x90,
	0xd8, 0x19, 0xaa, 0x88, 0xc1, 0x39, 0xd8, 0xa3, 0xac, 0xe4, 0x95, 0xb7, 0x7b, 0x62, 0x9f, 0xce,
	0xc2, 0xa3, 0x5e, 0xe1, 0x03, 0x63, 0x15, 0x5f, 0xaa, 0xbc, 0x26, 0xb1, 0x91, 0xe1, 0x0b, 0xf0,
	0xd0, 0xec, 0xa4, 0xbf, 0xbd, 0x3d, 0xed, 0x7e, 0xd6, 0x2b, 0x0c, 0x8d, 0x7b, 0x22, 0x92, 0x18,
	0xe8, 0xee, 0x6a, 0x68, 0x60, 0x02, 0x66, 0xb4, 0x14, 0x6d, 0x25, 0x13, 0x5e, 0x79, 0x8e, 0xc6,
	0xc2, 0xb5, 0xc2, 0xd6, 0x4f, 0x85, 0xe7, 0x0b, 0x2e, 0x3f, 0xb5, 0xa9, 0x9f, 0x89, 0x32, 0xc8,
	0x44, 0x53, 0x8a, 0x66, 0x7c, 0xce, 0x1a, 0x76, 0x13, 0xc8, 0xdb, 0x65, 0xde, 0xf8, 0x51, 0x25,
	0x7b, 0x85, 0x8f, 0x4c, 0xc8, 0xfd, 0x20, 0x12, 0xef, 0x9b, 0x3a, 0xaa, 0x60, 0x0a, 0xc0, 0xf8,
	0x2f, 0x5a, 0xe9, 0xb9, 0x3a, 0xe1, 0xd5, 0x7f, 0x27, 0x3c, 0xd9, 0x4a, 0x10, 0xad, 0x24, 0xf1,
	0xb8, 0xf7, 0x55, 0x2b, 0xc3, 0x0f, 0xeb, 0xdf, 0xc8, 0xfa, 0xde, 0x21, 0x6b, 0xdd, 0x21, 0xfb,
	0xae, 0x43, 0xf6, 0xaf, 0x0e, 0xd9, 0xdf, 0x36, 0xc8, 0xba, 0xdb, 0x20, 0xeb, 0xc7, 0x06, 0x59,
	0x1f, 0x2f, 0xb7, 0x92, 0x86, 0x4b, 0x3a, 0x13, 0xd7, 0xd7, 0x3c, 0xe3, 0xb4, 0x18, 0xfb, 0x60,
	0xfb, 0x06, 0x75, 0x78, 0xea, 0xe8, 0x53, 0xba, 0xf8, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xb7,
	0x5e, 0x45, 0xa6, 0x02, 0x00, 0x00,
}

func (m *LockedVault) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LockedVault) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LockedVault) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.AmountOut.Size()
		i -= size
		if _, err := m.AmountOut.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVault(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.AmountIn.Size()
		i -= size
		if _, err := m.AmountIn.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVault(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.VaultOwner) > 0 {
		i -= len(m.VaultOwner)
		copy(dAtA[i:], m.VaultOwner)
		i = encodeVarintVault(dAtA, i, uint64(len(m.VaultOwner)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintVault(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0x22
	}
	if m.PairID != 0 {
		i = encodeVarintVault(dAtA, i, uint64(m.PairID))
		i--
		dAtA[i] = 0x18
	}
	if m.VaultID != 0 {
		i = encodeVarintVault(dAtA, i, uint64(m.VaultID))
		i--
		dAtA[i] = 0x10
	}
	if m.LockedVaultID != 0 {
		i = encodeVarintVault(dAtA, i, uint64(m.LockedVaultID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintVault(dAtA []byte, offset int, v uint64) int {
	offset -= sovVault(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *LockedVault) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.LockedVaultID != 0 {
		n += 1 + sovVault(uint64(m.LockedVaultID))
	}
	if m.VaultID != 0 {
		n += 1 + sovVault(uint64(m.VaultID))
	}
	if m.PairID != 0 {
		n += 1 + sovVault(uint64(m.PairID))
	}
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = len(m.VaultOwner)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = m.AmountIn.Size()
	n += 1 + l + sovVault(uint64(l))
	l = m.AmountOut.Size()
	n += 1 + l + sovVault(uint64(l))
	return n
}

func sovVault(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVault(x uint64) (n int) {
	return sovVault(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LockedVault) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVault
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: locked_vault: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: locked_vault: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockedVaultID", wireType)
			}
			m.LockedVaultID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LockedVaultID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VaultID", wireType)
			}
			m.VaultID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VaultID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PairID", wireType)
			}
			m.PairID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PairID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VaultOwner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VaultOwner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountIn", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountIn.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AmountOut", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AmountOut.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVault(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVault
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVault(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVault
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVault
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVault
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVault
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVault
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVault
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVault        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVault          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVault = fmt.Errorf("proto: unexpected end of group")
)
